[package]
name = "glam-macros"
version = "0.20.2" # remember to update html_root_url
edition = "2018"
authors = ["Cameron Hart <cameron.hart@gmail.com>"]
license = "MIT OR Apache-2.0"

[lib]
proc-macro = true